/**
 * GENESIS PART VI - PHASE 60.D: N8N AUTHENTICATION & ACCESS CONTROL
 * n8n Configuration Generator
 * 
 * Generates docker-compose configuration for n8n with User Management
 */

import type { N8nEnvironmentConfig } from './n8n-types';

/**
 * n8n Configuration Generator
 * Generates secure n8n environment configuration
 */
export class N8nConfigGenerator {
  /**
   * Generate n8n environment variables for docker-compose
   */
  static generateEnvironmentConfig(
    n8nHost: string,
    encryptionKey: string,
    jwtSecret: string,
    smtpConfig?: {
      host: string;
      port: number;
      user: string;
      pass: string;
      sender: string;
    }
  ): N8nEnvironmentConfig {
    const config: N8nEnvironmentConfig = {
      n8n_host: n8nHost,
      n8n_encryption_key: encryptionKey,
      n8n_jwt_secret: jwtSecret,
    };

    if (smtpConfig) {
      config.smtp_host = smtpConfig.host;
      config.smtp_port = smtpConfig.port;
      config.smtp_user = smtpConfig.user;
      config.smtp_pass = smtpConfig.pass;
      config.smtp_sender = smtpConfig.sender;
    }

    return config;
  }

  /**
   * Generate docker-compose environment array
   */
  static generateDockerComposeEnvironment(config: N8nEnvironmentConfig): string[] {
    const env: string[] = [
      `N8N_HOST=${config.n8n_host}`,
      `N8N_ENCRYPTION_KEY=${config.n8n_encryption_key}`,
      
      // User Management (required in n8n 1.0+)
      'N8N_USER_MANAGEMENT_DISABLED=false',
      `N8N_USER_MANAGEMENT_JWT_SECRET=${config.n8n_jwt_secret}`,
    ];

    // SMTP configuration (optional)
    if (config.smtp_host) {
      env.push(
        'N8N_EMAIL_MODE=smtp',
        `N8N_SMTP_HOST=${config.smtp_host}`,
        `N8N_SMTP_PORT=${config.smtp_port}`,
        `N8N_SMTP_USER=${config.smtp_user}`,
        `N8N_SMTP_PASS=${config.smtp_pass}`,
        `N8N_SMTP_SENDER=${config.smtp_sender}`
      );
    }

    return env;
  }

  /**
   * Generate full docker-compose.yaml content
   */
  static generateDockerCompose(config: N8nEnvironmentConfig): string {
    const envVars = this.generateDockerComposeEnvironment(config);
    const envString = envVars.map(e => `      - ${e}`).join('\n');

    return `version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
${envString}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network

volumes:
  n8n_data:

networks:
  n8n_network:
    driver: bridge
`;
  }

  /**
   * Generate .env file content
   */
  static generateEnvFile(config: N8nEnvironmentConfig): string {
    const lines: string[] = [
      '# n8n Configuration',
      '# Generated by Genesis',
      '',
      `N8N_HOST=${config.n8n_host}`,
      `N8N_ENCRYPTION_KEY=${config.n8n_encryption_key}`,
      `N8N_JWT_SECRET=${config.n8n_jwt_secret}`,
    ];

    if (config.smtp_host) {
      lines.push(
        '',
        '# SMTP Configuration (optional)',
        `SMTP_HOST=${config.smtp_host}`,
        `SMTP_PORT=${config.smtp_port}`,
        `SMTP_USER=${config.smtp_user}`,
        `SMTP_PASS=${config.smtp_pass}`,
        `SMTP_SENDER=${config.smtp_sender}`
      );
    }

    return lines.join('\n') + '\n';
  }

  /**
   * Validate environment configuration
   */
  static validateConfig(config: N8nEnvironmentConfig): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    // Validate required fields
    if (!config.n8n_host || config.n8n_host.trim().length === 0) {
      errors.push('n8n_host is required');
    }

    if (!config.n8n_encryption_key || config.n8n_encryption_key.length < 32) {
      errors.push('n8n_encryption_key must be at least 32 characters');
    }

    if (!config.n8n_jwt_secret || config.n8n_jwt_secret.length < 32) {
      errors.push('n8n_jwt_secret must be at least 32 characters');
    }

    // Validate SMTP if provided
    if (config.smtp_host) {
      if (!config.smtp_port || config.smtp_port < 1 || config.smtp_port > 65535) {
        errors.push('Invalid SMTP port');
      }

      if (!config.smtp_user || config.smtp_user.trim().length === 0) {
        errors.push('SMTP user is required when SMTP is configured');
      }

      if (!config.smtp_pass || config.smtp_pass.trim().length === 0) {
        errors.push('SMTP password is required when SMTP is configured');
      }

      if (!config.smtp_sender || config.smtp_sender.trim().length === 0) {
        errors.push('SMTP sender is required when SMTP is configured');
      }
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }
}
