/**
 * Supabase Database Types (Auto-Generated Stub)
 *
 * This file is normally auto-generated by:
 *   npx supabase gen types typescript --linked > lib/database.types.ts
 *
 * This stub provides the minimum type definitions needed for TypeScript
 * compilation. Run the above command against your linked Supabase project
 * to regenerate with full table/view/function type definitions.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

/**
 * Generic table shape that matches Supabase's GenericTable constraint.
 * Must include Relationships[] to satisfy the extends check.
 */
type GenericTableDef = {
  Row: Record<string, any>;
  Insert: Record<string, any>;
  Update: Record<string, any>;
  Relationships: Array<{
    foreignKeyName: string;
    columns: string[];
    isOneToOne: boolean;
    referencedRelation: string;
    referencedColumns: string[];
  }>;
};

type GenericViewDef = {
  Row: Record<string, any>;
  Relationships: Array<{
    foreignKeyName: string;
    columns: string[];
    isOneToOne: boolean;
    referencedRelation: string;
    referencedColumns: string[];
  }>;
};

type GenericFunctionDef = {
  Args: Record<string, unknown>;
  Returns: unknown;
};

export interface Database {
  public: {
    Tables: Record<string, GenericTableDef>;
    Views: Record<string, GenericViewDef>;
    Functions: Record<string, GenericFunctionDef>;
    Enums: Record<string, string>;
    CompositeTypes: Record<string, unknown>;
  };
  genesis: {
    Tables: Record<string, GenericTableDef>;
    Views: Record<string, GenericViewDef>;
    Functions: Record<string, GenericFunctionDef>;
    Enums: Record<string, string>;
    CompositeTypes: Record<string, unknown>;
  };
}
